version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trapchat
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql  # Stocke les données dans un dossier local
      - ../sql/database-init.sql:/docker-entrypoint-initdb.d/database.sql