version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_memory_pagecache_size: 512M
      NEO4J_dbms.memory.heap.initial_size: 512M
      NEO4J_dbms.memory.heap.max_size: 1024M
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
      - ./neo4j_conf:/var/lib/neo4j/conf
      - ./neo4j_plugins:/plugins
